//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdexLab {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdexLab.MainResource", typeof(MainResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon idex {
            get {
                object obj = ResourceManager.GetObject("idex", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDEX
        ///ServerId = IdexServer
        ///ClientId = IdexClient
        ///g Server.Id.
        /// </summary>
        internal static string Request_1 {
            get {
                return ResourceManager.GetString("Request_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDEX
        ///ServerId = IdexServer
        ///ClientId = IdexClient
        ///g Server.State.
        /// </summary>
        internal static string Request_2 {
            get {
                return ResourceManager.GetString("Request_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDEX
        ///
        ///o CR=[
        ///g CR
        ///o ]
        ///
        ///g NL
        ///o LF=[
        ///g LF
        ///o ]
        ///
        ///g NL
        ///o HT=[
        ///g HT
        ///o ]
        ///
        ///g NL
        ///o SP=[
        ///g SP
        ///o ]
        ///
        ///g NL
        ///o CO=[
        ///g CO
        ///o ]
        ///
        ///g NL
        ///o SC=[
        ///g SC
        ///o ]
        ///
        ///g NL
        ///o FS=[
        ///g FS
        ///o ]
        ///
        ///g NL
        ///o SO=[
        ///g SO
        ///o ]
        ///
        ///g NL
        ///o RS=[
        ///g RS
        ///o ]
        ///
        ///g NL
        ///o a.text=[
        ///g a.text
        ///o ]
        ///
        ///g NL
        ///o a.line=[
        ///g a.line
        ///o ]
        ///
        ///g NL
        ///o a.col=[
        ///g a.col
        ///o ]
        ///
        ///g NL
        ///o a.topline=[
        ///g a.topline
        ///o ]
        ///
        ///g NL
        ///o a.bottomline=[
        ///g a.bottomline
        ///o ]
        ///
        ///g NL
        ///o a.rangecount=[
        ///g a.rangecount
        ///o ]
        ///
        ///g NL
        ///o a.topchar=[
        ///g a.topc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Request_All {
            get {
                return ResourceManager.GetString("Request_All", resourceCulture);
            }
        }
    }
}
